#!/usr/bin/env bash
# config domain zone so that subdomain points to load balancer IP
dns_info() {
	ANSWER=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
	echo  "$2 $ANSWER" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]; then
	dns_info "$1" "www"
	dns_info "$1" "lb-01"
	dns_info "$1" "web-01"
	dns_info "$1" "web-02"
elif [ "$#" == 2 ]; then
		dns_info "$1" "$2"
fi