#!/usr/bin/env bash
# install HAproxy load balancer

# install haproxy
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.8
apt-get install haproxy=2.8.\*

# change haproxy config
echo "frontend www-http
        bind *:80
        mode http
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 111427-web-01 54.175.44.151:80 check
        server 111427-web-02 34.232.66.141:80 check" >> /etc/haproxy/haproxy.cfg

# 
sudo chmod +x /etc/init.d/haproxy

# start haproxy service
sudo servicd haproxy start
