#!/usr/bin/env bash
# install HAproxy load balancer

# install haproxy
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get install haproxy=2.8.\*

# change haproxy config
config=\
"
frontend www-http
        bind *:80
        mode http
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 111427-web-01 54.175.44.151:80 check
        server 111427-web-02 34.232.66.141:80 check
"
echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# start haproxy service
sudo service haproxy start
