#!/usr/bin/env bash
# Use debugging to find out what’s keeping your Ubuntu container’s Nginx
sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
service nginx restart
kill -9 "$(cat /var/run/nginx.pid)"
