#!/usr/bin/env bash
#loop and display string(s)
for i in {1..100}; do
    three=$((i%3))
    five=$((i%5))

    if [ $five -eq 0 ] && [ $three -eq 0 ]; then
        echo "FizzBuzz"
    elif [ $three -eq 0 ]; then
        echo "Fizz"
    else
        echo "$i"
    fi
done