#!/usr/bin/env bash
# display numbers 1-100, FizzBuzz when number is multiple
# of 3 & 5, Fizz when a multiple of 3 & Buzz when number
# is multiple of 5

for number in {1..100}; do
	if (( number % 3 == 0 && number % 5 == 0 )); then
		echo "FizzBuzz"
	elif (( number % 3 == 0 )); then
			echo "Fizz"
		elif (( number % 5 == 0 )); then
				echo "Buzz"
			else
				echo "$number"
	fi
done