#!/usr/bin/env bash
# install ufw firewall & setup some rules on web-01

# udpate system & install ufw
sudo apt-get update
sudo apt-get install -y ufw

# config ufw to block all incoming traffic
sudo ufw default deny incoming

# allow incoming traffic on specific ports
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80

# enable ufw
sudo ufw enable