#!/usr/bin/env bash

# This script changes the localhost address
cp /etc/hosts ~/hosts.new
echo "127.0.0.2 local" > ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
